local_backend: true
backend:
  name: github
  repo: 1st-Chertsey-Scout-Group/1stchertsey.com
  branch: main
  squash_merges: true
media_folder: "src/media"
collections:
  - name: "section" # Used in routes, e.g., /admin/collections/blog
    label: "Section" # Used in the UI
    folder: "src/content/sections"
    identifier_field: title
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "string"

      - name: "meeting"
        label: "Meeting"
        widget: "object"
        collapsed: true
        summary: "{{fields.day}}: {{fields.start}} to {{fields.end}}"
        fields:
          - label: "Day"
            name: "day"
            widget: "select"
            options:
              [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday",
              ]

          - label: "Start Time"
            name: "start"
            widget: time

          - label: "End Time"
            name: "end"
            widget: time

      - label: "Link Group"
        name: "groups"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"

          - label: "Links"
            name: "links"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - label: "Url"
                name: "url"
                widget: "string"

              - label: "Image"
                name: "image"
                widget: "image"
                required: false

              - label: "Title"
                name: "title"
                widget: "string"

              - label: "Description"
                name: "description"
                widget: "string"
