backend:
  name: github
  repo: 1st-Chertsey-Scout-Group/1stchertsey.com
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "redirects" # Used in routes, e.g., /admin/collections/blog
    label: "Redirects" # Used in the UI
    folder: "src/content/redirects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: json
    format: json
    slug: "{{from}}"
    summary: "{{from}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "From", name: "from", widget: "string" }
      - { label: "To", name: "to", widget: "string" }
      - { label: "Status", name: "status", widget: "number", default: 200 }
      - { label: "Force", name: "force", widget: "boolean", default: false }